services:
  db-test:
    image: mysql:9.4.0
    env_file: .env.test
    ports:
      - "33062:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db-test:/var/lib/mysql

  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.test
    ports:
      - "8082:8080"
    depends_on:
      db-test:
        condition: service_healthy
    volumes:
      - ./images:/app/images
      - ./test-data:/app/test-data:ro

volumes:
  db-test:
