services:
  db:
    env_file: .env
    image: mysql:9.4.0
    ports:
      - ${MYSQL_PORT:-33061}:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db:/var/lib/mysql

  nginx:
    image: nginx:1.29.2
    ports:
      - ${NGINX_PORT:-8081}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${IMAGES_BASE_PATH:-./images}:/var/www/images

volumes:
  db:
