services:
  db-test:
    image: mysql:9.4.0
    env_file: .env.test
    command: [
      "mysqld",
      "--log-bin-trust-function-creators=1"
    ]
    ports:
      - "33062:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db-test:/var/lib/mysql

volumes:
  db-test:
