[versions]
asciidoctorVersion = "3.3.2"
dotenvVersion = "3.2.0"
jjwtVersion = "0.13.0"
lombokVersion = "1.18.40"
mysqlConnectorVersion = "9.4.0"
openAPIVersion = "2.8.13"
springFrameworkVersion = "3.5.5"
springDepManagerVersion = "1.1.7"
jsonSchemaValidatorVersion = "2.0.0"

[libraries]
dotenv = { group = "io.github.cdimascio", name = "dotenv-java", version.ref = "dotenvVersion" }
flyway-core = { group = "org.flywaydb", name = "flyway-core" }
flyway-mysql = { group = "org.flywaydb", name = "flyway-mysql" }
junit-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
jjwt-api = { group = "io.jsonwebtoken", name = "jjwt-api", version.ref = "jjwtVersion" }
jjwt-impl = { group = "io.jsonwebtoken", name = "jjwt-impl", version.ref = "jjwtVersion" }
jjwt-jackson = { group = "io.jsonwebtoken", name = "jjwt-jackson", version.ref = "jjwtVersion" }
json-schema-validator = { group = "com.networknt", name = "json-schema-validator", version.ref = "jsonSchemaValidatorVersion" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombokVersion" }
mysql-connector = { group = "com.mysql", name = "mysql-connector-j", version.ref = "mysqlConnectorVersion" }
openApi = { group = "org.springdoc", name = "springdoc-openapi-starter-webmvc-ui", version.ref = "openAPIVersion" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor" }
spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-devtools" }
spring-boot-docker-compose = { group = "org.springframework.boot", name = "spring-boot-docker-compose" }
spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator" }
spring-boot-starter-data-jdbc = { group = "org.springframework.boot", name = "spring-boot-starter-data-jdbc" }
spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
spring-boot-starter-security = { group = "org.springframework.boot", name = "spring-boot-starter-security" }
spring-boot-starter-test = { group = "org.springframework.boot", name = "spring-boot-starter-test" }
spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
spring-boot-starter-web = { group = "org.springframework.boot", name = "spring-boot-starter-web" }
spring-restdocs-mockmvc = { group = "org.springframework.restdocs", name = "spring-restdocs-mockmvc" }
spring-security-test = { group = "org.springframework.security", name = "spring-security-test" }

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctorVersion" }
spring-boot = { id = "org.springframework.boot", version.ref = "springFrameworkVersion" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "springDepManagerVersion" }
